# Site settings
title:                Zealous Landing Page Generator
email:                your-email@domain.com
description:          > # this means to ignore newlines until "baseurl:"
                      A jekyll static site meant for generating quick page
                      layouts to make landing pages in a quicker manner.

baseurl: "/zealous" # the subpath of your site, e.g. /blog
url: "http://este-tea.github.io/zealous" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
