# Site settings
title: Zealous Landing Page Generator
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A jekyll static site meant for generating quick page layouts to make landing
  pages in a quicker manner.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  este-tea

# Build settings
markdown: kramdown
